# -*- coding: utf-8 -*-
"""segunda entrega.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l2rdC-vnTy0ImvN5tY6vvxq33tFN3K_o
"""

#para empezar con el proyecto, importamos todas la librerias que sean necesarias.
import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import requests
import zipfile
import io
import os
import matplotlib.pyplot as plt
import seaborn as sns

"""#Importación y unión de datos.

dentro de nuestro análisis, buscamos agregar más información con diferentes fuentes de datos. Al intentar unir, observamos que los datos registrados son menores, y por consecuencia nuestra base de datos original crea información nula para llenar esos vacios, por eso se tomó la decisión de hacer el análisis con la base de datos original
"""

#nuestra base de datos está dentro de google drive, por esa razón debemos llamarlo dentro de este cuaderno.
from google.colab import drive, files
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Dataset'
os.chdir(path)

#la base de datos se llama "vehiculos_involucrados_en_un_accidente_de_transito". Esta base de datos guiará todo el proyecto ya que contiene
#los datos necesarios, como lo es: marca del vehiculo, modelo del vehiculo, tipo de vehiculo, edad del vehiculo, fecha, etc.
df = pd.read_csv('VEHICULOS_INVOLUCRADOS_EN_UN_ACCIDENTE_DE_TRANSITO_LEY_2251-2022_20260406.csv', encoding ='utf-8', dtype=str) #latin-1
df.head()

df.shape

"""#Limpieza y Preparación de datos"""

#verificamos si la base de datos cuenta con valores nulos, a partir del resultado se decide la eliminación de los valores nulos.
df.isnull().sum()

#Los valores nulos no tienen mayor participación dentro de la base de datos, se toma la decisión de eliminarlos.
df = df.dropna()

#revisamos si estos quedaron eliminados
df.isnull().sum()

#ahora queremos saber con que cantidad de filas y columnas cuenta la base de datos con la eliminación de los valores nulos y vemos que no hubo mayor cambio dentro de la base de datos.
df.shape

#dentro de la base de datos existe una variable que mezcla el año con el mes.
#se toma la decisión de separar estas variables para tener un mejor análisis, obteninedo asi dos nuevas columnas.
df['FECHA_ACCIDENTE'] = pd.to_datetime(df['FECHA_ACCIDENTE'], format='%m/%Y', errors='coerce')
df['año'] = df['FECHA_ACCIDENTE'].dt.year
df['mes'] = df['FECHA_ACCIDENTE'].dt.month

df.head()

#contamos las filas y columnas de la base de datos para asegurarnos que este haya cambiado
df.shape

#una variable muy importante dentro de la base de datos es "gravedad_accidente", esta variable es la más importante dentro de nuestro análisis
#porque determina si un accidente de transito tuvo victimas fatales, pero no queremos manejarla como una variable categórica sino como una numerica
#por esa razón la convertimos en una variable dummy, a través del mecanismo one hot encoding.
df['fatal'] = df['GRAVEDAD_ACCIDENTE'].apply(lambda x: 1 if x == 'CON MUERTOS' else 0)

#aqui observamos como la nueva variable dummy tiene su participación dentro de la base de datos.
df[400000:402000]

#contamos cuantos accidentes "con muertos" hay registrados
(df['GRAVEDAD_ACCIDENTE'] == 'CON MUERTOS').sum()

#ahora nos aseguramos que la variable dummy coincida con el anterior numero de victimas fatales
(df['fatal'] == 1).sum()

#encontramos que la variable "edad vehiculo" es categórica, por esta razón debemos cambiarla a una variable numérica.
#al convertirla en variable numérica debemos eliminar todos los valores nulos que esten dentro.
#hay edades de vehiculos que no tienen sentido dentro del análisis, en necesario borrar los datos que no tengan relevancia, por esta razon solo dejamos vehiculos con edades menores a 50
df['EDAD_VEHICULO'] = pd.to_numeric(df['EDAD_VEHICULO'], errors='coerce')
df = df.dropna(subset=['EDAD_VEHICULO'])
df = df[df['EDAD_VEHICULO'] < 50]

#revisamos los cambios dentro de la base de datos
df.shape

"""#Analisis Exploratorio de Datos (EDA)

analisis univariado
"""

# la gráfica que usamos muestra la comparación entre accidentes con victimas fatales y victimas no fatales
if 'fatal' not in df.columns and 'GRAVEDAD_ACCIDENTE' in df.columns:
    df['fatal'] = df['GRAVEDAD_ACCIDENTE'].apply(lambda x: 1 if x == 'CON MUERTOS' else 0)

sns.countplot(x='fatal', data=df)
plt.title("Distribución de accidentes fatales vs no fatales")
plt.xlabel("Fatal (0 = no, 1 = sí)")
plt.ylabel("Número de accidentes")
plt.show()

# miramos la cantidades exactas de cada resultado
df['fatal'].value_counts()

# la base de datos proporciona información sobre los tipos de vehiculos que han estado involucrados en un accidente de transito
# queremos averiguar cuales vehiculos tienen el mayor registro de accidentes
orden = df['TIPO_VEHICULO'].value_counts().index
plt.figure(figsize=(14, 6))
sns.countplot(
    x='TIPO_VEHICULO',
    data=df,
    order=orden
)
plt.xticks(rotation=45, ha='right')
plt.title("Accidentes por tipo de vehículo")
plt.xlabel("Tipo de vehículo")
plt.ylabel("Número de accidentes")
plt.tight_layout()
plt.show()

# datos exactos de los registros
df['TIPO_VEHICULO'].value_counts()

# el modelo del vehiculo es importante para el análisis, queremos mostrar que modelo se ha involucrado en la mayor cantidad de accidentes
orden = df['MODELO_VEHICULO'].value_counts().index
plt.figure(figsize=(16, 6))
sns.countplot(
    x='MODELO_VEHICULO',
    data=df,
    order=orden
)
plt.xticks(rotation=45, ha='right')
plt.title("Accidentes por modelo del vehículo")
plt.xlabel("Modelo del vehículo")
plt.ylabel("Número de accidentes")
plt.tight_layout()
plt.show()

df['MODELO_VEHICULO'].value_counts()

# la edad del vehiculo es importante para conocer su participacion dentro de accidentes de transito, mostrando que edad es más propensa a tener accidentes
orden = df['EDAD_VEHICULO'].value_counts().index
plt.figure(figsize=(14, 6))
sns.countplot(
    x='EDAD_VEHICULO',
    data=df,
    order=orden
)
plt.xticks(rotation=45, ha='right')
plt.title("Accidentes por edad del vehículo")
plt.xlabel("Edad del vehículo")
plt.ylabel("Número de accidentes")
plt.tight_layout()
plt.show()

df['EDAD_VEHICULO'].value_counts()

# la diferencia geográfica entre departamentos es una varible importante dentro del análisis.
# este gráfico muestra los departamentos que tienen mayor cantidad de accidentes.
orden = df['DEPARTAMENTO_ACCIDENTE'].value_counts().index
plt.figure(figsize=(18, 6))
sns.countplot(
    x='DEPARTAMENTO_ACCIDENTE',
    data=df,
    order=orden
)
plt.xticks(rotation=45, ha='right')
plt.title("Accidentes por departamento")
plt.xlabel("Departamento")
plt.ylabel("Número de accidentes")
plt.tight_layout()
plt.show()

df['DEPARTAMENTO_ACCIDENTE'].value_counts()

# queremos identifica patrones temporales y estacionales en los accidentes de transito.
# hay meses que muestran mayores registros de accidentes de transito, estos se deben a cambio climaticos, turismo, vacaciones o flujo vehicular
meses = {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre'
}
df['mes_nombre'] = df['mes'].map(meses)
orden = df['mes_nombre'].value_counts().index
plt.figure(figsize=(14, 6))
sns.countplot(
    x='mes_nombre',
    data=df,
    order=orden
)
plt.xticks(rotation=45, ha='right')
plt.title("Accidentes por mes")
plt.xlabel("Mes")
plt.ylabel("Número de accidentes")
plt.tight_layout()
plt.show()

df['mes'].value_counts()

# conocer los años ayuda a detectar si los accidentes de transito han disminuido o aumentado, evaluar el impacto de las políticas de seguridad vial, cambios en infraestructura o crecimiento del parque automotor
sns.countplot(x='año', data=df)
plt.xticks(rotation=45)
plt.title("Accidentes por año")
plt.show()

df['año'].value_counts()

"""##Análisis bivariado

despues de conocer la información general, nos vamos a enfocar en la comparación de accidentes con victimas fatales y accidentes sin victimas fatales
"""

# Comparar accidentes fatales y no fatales según el mes sirve para identificar si existen períodos del año en los que no solo aumentan los accidentes, sino también su gravedad.
meses = {
    1: 'Enero',
    2: 'Febrero',
    3: 'Marzo',
    4: 'Abril',
    5: 'Mayo',
    6: 'Junio',
    7: 'Julio',
    8: 'Agosto',
    9: 'Septiembre',
    10: 'Octubre',
    11: 'Noviembre',
    12: 'Diciembre'
}
df['mes_nombre'] = df['mes'].map(meses)
tabla_abs = pd.crosstab(df['mes_nombre'], df['fatal'])
tabla_pct = tabla_abs / len(df) * 100
tabla_pct = tabla_pct.sort_values(by=1, ascending=False)
tabla_pct = tabla_pct.rename(columns={
    0: 'Heridos',
    1: 'Muertos'
})
tabla_pct.plot(
    kind='bar',
    stacked=True,
    figsize=(14, 6)
)
plt.title("Accidentes fatales según el mes (% del total de accidentes)")
plt.xlabel("Mes")
plt.ylabel("Porcentaje del total de accidentes (%)")
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resultado')
plt.tight_layout()
plt.show()

df[df['fatal'] == 1].groupby('mes').size()
pd.crosstab(df['mes'], df['fatal'])

#Este análisis ayuda a determinar si los accidentes fatales representan una parte cada vez mayor o menor del total de accidentes
tabla_abs = pd.crosstab(df['año'], df['fatal'])
tabla_pct = tabla_abs / len(df) * 100
tabla_pct = tabla_pct.sort_values(by=1, ascending=False)
tabla_pct = tabla_pct.rename(columns={
    0: 'Heridos',
    1: 'Muertos'
})
tabla_pct.plot(
    kind='bar',
    stacked=True,
    figsize=(12, 6)
)
plt.title("Accidentes fatales según el año (% del total de accidentes)")
plt.xlabel("Año")
plt.ylabel("Porcentaje del total de accidentes (%)")
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resultado')
plt.tight_layout()
plt.show()

df[df['fatal'] == 1].groupby('año').size()
pd.crosstab(df['año'], df['fatal'])

#Comparar la proporción de accidentes fatales y no fatales según el tipo de vehículo permite identificar cuáles vehículos están más asociados a accidentes de alta gravedad.
tabla_abs = pd.crosstab(df['TIPO_VEHICULO'], df['fatal'])
tabla_pct = tabla_abs / len(df) * 100
tabla_pct = tabla_pct.sort_values(by=1, ascending=False)
tabla_pct = tabla_pct.rename(columns={
    0: 'Heridos',
    1: 'Muertos'
})
tabla_pct.plot(
    kind='bar',
    stacked=True,
    figsize=(18, 7)
)
plt.title("Accidentes fatales por tipo de vehículo (% del total de accidentes)")
plt.xlabel("Tipo de vehículo")
plt.ylabel("Porcentaje del total de accidentes (%)")
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resultado')
plt.tight_layout()
plt.show()

df[df['fatal'] == 1].groupby('TIPO_VEHICULO').size()
pd.crosstab(df['TIPO_VEHICULO'], df['fatal'])

#Comparar la proporción de accidentes fatales y no fatales según la edad del vehículo permite analizar si la antigüedad de los vehículos influye en la gravedad de los accidentes. Este análisis ayuda a identificar si los vehículos más antiguos presentan una mayor participación en accidentes fatales debido a factores como desgaste mecánico, menor incorporación de tecnologías de seguridad o deficiencias en el mantenimiento.
tabla_abs = pd.crosstab(df['EDAD_VEHICULO'], df['fatal'])
tabla_pct = tabla_abs / len(df) * 100
tabla_pct = tabla_pct.sort_values(by=1, ascending=False)
tabla_pct = tabla_pct.rename(columns={
    0: 'Heridos',
    1: 'Muertos'
})
tabla_pct.plot(
    kind='bar',
    stacked=True,
    figsize=(20, 7)
)
plt.title("Accidentes fatales por edad del vehículo (% del total de accidentes)")
plt.xlabel("Edad del vehículo")
plt.ylabel("Porcentaje del total de accidentes (%)")
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resultado')
plt.tight_layout()
plt.show()

df[df['fatal'] == 1].groupby('EDAD_VEHICULO').size()
pd.crosstab(df['EDAD_VEHICULO'], df['fatal'])

#Comparar la proporción de accidentes fatales y no fatales por departamento permite identificar diferencias territoriales en la severidad de los accidentes de tránsito y detectar regiones con mayores niveles de riesgo vial. Este análisis ayuda a evaluar cómo factores como la infraestructura, el estado de las vías, las condiciones geográficas, el flujo vehicular y las políticas locales de tránsito pueden influir en la mortalidad vial.
tabla_abs = pd.crosstab(df['DEPARTAMENTO_ACCIDENTE'], df['fatal'])
tabla_pct = tabla_abs / len(df) * 100
tabla_pct = tabla_pct.sort_values(by=1, ascending=False)
tabla_pct = tabla_pct.rename(columns={
    0: 'Heridos',
    1: 'Muertos'
})
tabla_pct.plot(
    kind='bar',
    stacked=True,
    figsize=(22, 8)
)
plt.title("Accidentes fatales por departamento (% del total de accidentes)")
plt.xlabel("Departamento")
plt.ylabel("Porcentaje del total de accidentes (%)")
plt.xticks(rotation=45, ha='right')
plt.legend(title='Resultado')
plt.tight_layout()
plt.show()

df[df['fatal'] == 1].groupby('DEPARTAMENTO_ACCIDENTE').size()
pd.crosstab(df['DEPARTAMENTO_ACCIDENTE'], df['fatal'])

df_numeric = df[['EDAD_VEHICULO', 'año', 'mes', 'fatal']]
correlation_matrix = df_numeric.corr()
correlation_matrix

"""haremos un mapa de calor que muestre los departamentos que tienen mayor probabilidad de fatalidad en un accidente de transito"""

#primero revisamos como estan escritos los departamentos dentro de nuestra base de datos original
df['DEPARTAMENTO_ACCIDENTE'].unique()

# convertimos los departamentos en strings y los ponemos en minusculas, esto con el fin de conectar con la base de datos del mapa de los departamentos de Colombia
df['DEPARTAMENTO_ACCIDENTE'] = (
    df['DEPARTAMENTO_ACCIDENTE']
    .astype(str)
    .str.lower()
    .str.strip()
)

#iliminamos tildes y caracteres especiales
import unicodedata

df['DEPARTAMENTO_ACCIDENTE'] = (
    df['DEPARTAMENTO_ACCIDENTE']
    .astype(str)
    .str.lower()
    .str.strip()
    .apply(
        lambda x: unicodedata.normalize('NFKD', x)
        .encode('ascii', 'ignore')
        .decode('utf-8')
    )
)

#importamos el mapa de los departamentos de Colombia
shapefile_colombia_ruta = r"/content/drive/MyDrive/Dataset/MGN2023_DPTO_POLITICO"
colombia_mapa = gpd.read_file(shapefile_colombia_ruta)

colombia_mapa.plot(figsize=(10, 8), edgecolor='black', facecolor='none')
plt.title('Mapa base de Colombia', fontsize=14)
plt.axis('off')  # Opcional para eliminar los ejes
plt.show()

# miramos las variables
colombia_mapa

# revisamos como están registrados los departamentos
colombia_mapa['dpto_cnmbr']

#reemplazamos los nombres para que concuerden con los departamentos de nuestra base de datos original
reemplazos_departamentos = {
    'ANTIOQUIA': 'antioquia',
    'ATLÁNTICO': 'atlantico',
    'BOGOTÁ, D.C.': 'bogota d.c.',
    'BOLÍVAR': 'bolivar',
    'BOYACÁ': 'boyaca',
    'CALDAS': 'caldas',
    'CAQUETÁ': 'caqueta',
    'CAUCA': 'cauca',
    'CESAR': 'cesar',
    'CÓRDOBA': 'cordoba',
    'CUNDINAMARCA': 'cundinamarca',
    'CHOCÓ': 'choco',
    'HUILA': 'huila',
    'LA GUAJIRA': 'la guajira',
    'MAGDALENA': 'magdalena',
    'META': 'meta',
    'NARIÑO': 'narino',
    'NORTE DE SANTANDER': 'norte de santander',
    'QUINDIO': 'quindio',
    'RISARALDA': 'risaralda',
    'SANTANDER': 'santander',
    'SUCRE': 'sucre',
    'TOLIMA': 'tolima',
    'VALLE DEL CAUCA': 'valle del cauca',
    'ARAUCA': 'arauca',
    'CASANARE': 'casanare',
    'PUTUMAYO': 'putumayo',
    'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANT...':
        'archipielago de san andres, providencia',
    'AMAZONAS': 'amazonas',
    'GUAINÍA': 'guainia',
    'GUAVIARE': 'guaviare',
    'VAUPÉS': 'vaupes',
    'VICHADA': 'vichada'
}

colombia_mapa['dpto_cnmbr'] = (
    colombia_mapa['dpto_cnmbr']
    .replace(reemplazos_departamentos)
)

#creamos un nuevo df que contenga los departamentos de nuestra base de datos original y calcularemos la probabilidad de accidente fatal en cada uno

df_departamentos = (
    df
    .groupby('DEPARTAMENTO_ACCIDENTE')['GRAVEDAD_ACCIDENTE']

    # calcula proporción de "CON MUERTOS"
    .apply(lambda x: (x == 'CON MUERTOS').mean())

    .reset_index(name='PROB_FATAL')
)

# convertir a porcentaje
df_departamentos['PROB_FATAL']  = (
    df_departamentos['PROB_FATAL'].round(2)
)

# ordenar de mayor a menor
df_departamentos = df_departamentos.sort_values(
    by='PROB_FATAL',
    ascending=False
)

df_departamentos.head()

df_departamentos

#unimos el mapa de los departamentos con nuestra base de datos de departamentos que creamos anteriormente
colombia_accidentes = colombia_mapa.merge(
    df_departamentos,
    left_on='dpto_cnmbr',
    right_on='DEPARTAMENTO_ACCIDENTE',
    how='left'
)

#revisamos si está bien o debemos hacer algun cambio
colombia_accidentes

#el mapa de calor de los departamentos de Colombia está listo, podemos observar como algunos departamentos (Cesar y La Guajira) tienen mayor probabilidad de tener un accidente de transito fatal
fig, ax = plt.subplots(1, 1, figsize=(12, 8))

colombia_accidentes.plot(column='PROB_FATAL', cmap='Blues', linewidth=0.8, ax=ax, edgecolor='0.8', legend=True, missing_kwds={
    "color": "lightgrey",
    "edgecolor": "red",
    "hatch": "///",
    "label": "Sin datos"
})
colombia_accidentes.boundary.plot(ax=ax, color='black', linewidth=0.5, label='Límites departamentales')

ax.legend(loc='lower left')
ax.set_title('ACCIDENETES POR DEPARTAMENTO 2022-2026')
ax.axis('off')

plt.show()

import geopandas as gpd
import pandas as pd
import folium
from folium.features import GeoJsonTooltip
from branca.colormap import linear

colombia_accidentes = colombia_mapa.merge(
    df_departamentos,
    left_on='dpto_cnmbr',
    right_on='DEPARTAMENTO_ACCIDENTE',
    how='left'
)


colombia_accidentes['PROB_FATAL'] = (
    colombia_accidentes['PROB_FATAL']
    .fillna(0)
)


colombia_accidentes = colombia_accidentes.to_crs(epsg=4326)



m = folium.Map(
    location=[4.5, -74],
    zoom_start=5,
    tiles='CartoDB positron'
)

colormap = linear.Blues_09.scale(
    colombia_accidentes['PROB_FATAL'].min(),
    colombia_accidentes['PROB_FATAL'].max()
)

colormap.caption = 'Número de accidentes fatales'


def style_function(feature):

    fatal = feature['properties']['PROB_FATAL']

    return {
        'fillColor': colormap(fatal),
        'color': 'black',
        'weight': 1,
        'fillOpacity': 0.8
    }


tooltip = GeoJsonTooltip(
    fields=['dpto_cnmbr', 'PROB_FATAL'],
    aliases=['Departamento:', 'Probabilidad de fatalidad:'],
    localize=True,
    sticky=False,
    labels=True,
    style="""
        background-color: white;
        border: 2px solid black;
        border-radius: 5px;
        box-shadow: 3px;
        font-size: 14px;
        padding: 10px;
    """
)


geojson = folium.GeoJson(
    colombia_accidentes,
    style_function=style_function,
    tooltip=tooltip,
    highlight_function=lambda x: {
        'weight': 3,
        'fillOpacity': 1
    }
)

geojson.add_to(m)



colormap.add_to(m)

title_html = '''
<div style="
    position: fixed;
    top: 10px;
    left: 50px;
    width: 420px;
    height: 40px;
    z-index:9999;
    font-size:20px;
    font-weight:bold;
    background-color:white;
    border-radius:8px;
    padding:10px;
    border:2px solid grey;
">
🚗 Probabilidad de fatalidad por Departamento (2022-2026)
</div>
'''

m.get_root().html.add_child(
    folium.Element(title_html)
)


folium.LayerControl().add_to(m)

m

m.save('/content/mapa_accidentes_fatales.html')

from google.colab import drive
drive.mount('/content/drive')

"""#implementación y evaluación modelos

queremos comparar algunos modelos supervisados, y teniendo en cuenta su resultado, escogeremos el mejor modelo

balanceo

antes de entrenar los modelos, observamos que los regsitros están desbalanceados, la cantidad de accidentes fatales resgitra menos datos que la cantidad de accidentes no fatales. Este desbalanceo puede influir dentro del entrenamiento de los modelos, por esa razón decidimos que los datos deben estar con la misma cantidad de registros y así obtener un resultado con mayor predicción.
"""

# Separar clases
df_majority = df[df["fatal"] == 0]
df_minority = df[df["fatal"] == 1]

# Reducir la clase mayoritaria al tamaño de la minoritaria
df_majority_downsampled = df_majority.sample(
    n=len(df_minority),
    random_state=42
)

# Combinar ambas clases
df_balanced = pd.concat([df_majority_downsampled, df_minority])

# Mezclar filas
df_balanced = df_balanced.sample(frac=1, random_state=42).reset_index(drop=True)

# Verificar balance
print(df_balanced["fatal"].value_counts())

"""regresión logistica"""

variables = [
    'TIPO_VEHICULO',
    'EDAD_VEHICULO',
    'DEPARTAMENTO_ACCIDENTE',
    'mes',
    'año'
]

X = df_balanced[variables]

y = df_balanced['fatal']

variables_numericas = [
    'EDAD_VEHICULO',
    'mes',
    'año'
]

variables_categoricas = [
    'TIPO_VEHICULO',
    'DEPARTAMENTO_ACCIDENTE'
]

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

preprocesador = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            variables_numericas
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            variables_categoricas
        )
    ]
)

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression

pipeline_logit = Pipeline([
    ('preprocesamiento', preprocesador),
    ('modelo', LogisticRegression(
        max_iter=1000
    ))
])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

pipeline_logit.fit(
    X_train,
    y_train
)

y_pred = pipeline_logit.predict(X_test)

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Precision:", precision_score(y_test, y_pred))

print("Recall:", recall_score(y_test, y_pred))

print("F1-score:", f1_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

"""xgbost"""

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

X = df_balanced[variables]

y = df_balanced['fatal']

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

preprocesador = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            variables_numericas
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            variables_categoricas
        )
    ]
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import (
    StandardScaler,
    OneHotEncoder
)

preprocesador = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            variables_numericas
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            variables_categoricas
        )
    ]
)

from sklearn.pipeline import Pipeline

pipeline_xgb = Pipeline([
    ('preprocesamiento', preprocesador),

    ('modelo', XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric='logloss'
    ))
])

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

pipeline_xgb.fit(
    X_train,
    y_train
)

y_pred_xgb = pipeline_xgb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_xgb))

print("Precision:", precision_score(y_test, y_pred_xgb))

print("Recall:", recall_score(y_test, y_pred_xgb))

print("F1-score:", f1_score(y_test, y_pred_xgb))

print(classification_report(y_test, y_pred_xgb))

confusion_matrix(y_test, y_pred_xgb)

"""arboles de decision"""

from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import (classification_report, confusion_matrix,
                             ConfusionMatrixDisplay, roc_auc_score, roc_curve)

# Variables predictoras y objetivo
variables = [
    'TIPO_VEHICULO',
    'EDAD_VEHICULO',
    'DEPARTAMENTO_ACCIDENTE',
    'mes',
    'año'
]

X = df_balanced[variables].copy()
y = df_balanced['fatal']

# Codificar variables categóricas
le_tipo = LabelEncoder()
le_depto = LabelEncoder()

X['TIPO_VEHICULO'] = le_tipo.fit_transform(X['TIPO_VEHICULO'])
X['DEPARTAMENTO_ACCIDENTE'] = le_depto.fit_transform(X['DEPARTAMENTO_ACCIDENTE'])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print(f"Train: {X_train.shape[0]} filas | Test: {X_test.shape[0]} filas")

param_grid = {
    'max_depth': [3, 5, 7, 10, None],
    'min_samples_split': [2, 10, 20],
    'min_samples_leaf': [1, 5, 10],
    'criterion': ['gini', 'entropy']
}

dt = DecisionTreeClassifier(random_state=42)

grid_search = GridSearchCV(
    dt,
    param_grid,
    cv=5,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid_search.fit(X_train, y_train)

print("Mejores hiperparámetros:", grid_search.best_params_)
print(f"Mejor AUC (CV): {grid_search.best_score_:.4f}")

best_dt = grid_search.best_estimator_

y_pred = best_dt.predict(X_test)
y_prob = best_dt.predict_proba(X_test)[:, 1]

print("=" * 50)
print("CLASIFICACIÓN - ÁRBOL DE DECISIÓN")
print("=" * 50)
print(classification_report(y_test, y_pred, target_names=['No Fatal', 'Fatal']))
print(f"AUC-ROC: {roc_auc_score(y_test, y_prob):.4f}")

"""random forest"""

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, confusion_matrix, classification_report

features = [
    "TIPO_VEHICULO",
    "MARCA_VEHICULO",
    "EDAD_VEHICULO",
    "MUNICIPIO_ACCIDENTE",
    "DEPARTAMENTO_ACCIDENTE",
    "año",
    "mes",

]

X = df_balanced[features]
y = df_balanced["fatal"]


numeric_features = [
    "EDAD_VEHICULO",
    "año",
    "mes",
]

categorical_features = [
    "TIPO_VEHICULO",
    "MARCA_VEHICULO",
    "MUNICIPIO_ACCIDENTE",
    "DEPARTAMENTO_ACCIDENTE",
]


numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median"))
])


categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])


preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)


rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)


model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", rf)
])


model.fit(X_train, y_train)


y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]


print("========== RESULTADOS RANDOM FOREST ==========")
print(f"Accuracy : {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred):.4f}")
print(f"Recall   : {recall_score(y_test, y_pred):.4f}")
print(f"F1-Score : {f1_score(y_test, y_pred):.4f}")
print(f"ROC-AUC  : {roc_auc_score(y_test, y_prob):.4f}")

print("\n========== MATRIZ DE CONFUSIÓN ==========")
print(confusion_matrix(y_test, y_pred))

print("\n========== REPORTE DE CLASIFICACIÓN ==========")
print(classification_report(y_test, y_pred))

"""gradient boosting"""

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score
)
from sklearn.pipeline import Pipeline

# Variables predictoras y objetivo
X = df_balanced.drop(columns=['fatal'])
y = df_balanced['fatal']

# División entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Pipeline
pipeline_gb = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', GradientBoostingClassifier(random_state=42))
])

# Grilla de hiperparámetros
param_grid = {
    'classifier__n_estimators': [50, 100, 200],
    'classifier__learning_rate': [0.01, 0.05, 0.1],
    'classifier__max_depth': [3, 5, 7],
    'classifier__subsample': [0.8, 1.0]
}

# GridSearch con validación cruzada
grid_search = GridSearchCV(
    estimator=pipeline_gb,
    param_grid=param_grid,
    cv=5,                     # Validación cruzada de 5 folds
    scoring='f1',             # Métrica principal
    n_jobs=-1,
    verbose=2
)

# Entrenar
grid_search.fit(X_train, y_train)

# Mejor modelo
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_prob = best_model.predict_proba(X_test)[:, 1]

# Resultados
print("Mejores hiperparámetros:")
print(grid_search.best_params_)

print("\nMatriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred))

roc_auc = roc_auc_score(y_test, y_prob)
print(f"\nROC-AUC: {roc_auc:.4f}")

"""interpretacion y que modelo escogimos

1. Regresión Logística

Accuracy: 70.6%

Precision: 72.3%

Recall: 66.8%

F1-score: 69.4%

Interpretación:
Fue el modelo con el desempeño más básico, pero bastante equilibrado.
Tiene una buena precisión, lo que significa que cuando predice un accidente fatal suele acertar.
Sin embargo, el recall es más bajo, indicando que deja escapar varios casos positivos reales.
Es un modelo fácil de interpretar y útil como línea base, pero tiene limitaciones para capturar relaciones complejas entre variables.

2. XGBoost

Accuracy: 70.6%

Precision: 71.7%

Recall: 68.1%

F1-score: 69.9%

Interpretación
Presenta un rendimiento ligeramente superior a la regresión logística.
Mejora el recall, por lo que detecta más casos fatales reales.
El F1-score es un poco más alto, mostrando un mejor equilibrio entre precisión y sensibilidad.
Aun así, la mejora respecto a la regresión logística es pequeña.

3. Árbol de Decisión

Accuracy: 70%

F1-score: 70%

AUC-ROC: 0.7677

Interpretación
Tiene un desempeño similar a los modelos anteriores, pero ligeramente inferior.
Su principal ventaja es la interpretabilidad, ya que permite visualizar reglas de decisión.
Puede capturar relaciones no lineales entre variables.
Sin embargo, los árboles individuales suelen sobreajustarse y generalizar peor que modelos ensamblados.

4. Random Forest

Accuracy: 72.3%

Precision: 71.3%

Recall: 74.9%

F1-score: 73%

ROC-AUC: 0.8029

Interpretación
Fue uno de los modelos con mejor desempeño general.
Tiene un recall bastante alto, lo que significa que detecta una mayor cantidad de accidentes fatales reales.
El F1-score mejora considerablemente frente a los modelos anteriores.
El ROC-AUC superior a 0.80 indica una buena capacidad para diferenciar entre accidentes fatales y no fatales.
Al combinar múltiples árboles, reduce el sobreajuste y mejora la estabilidad de las predicciones.

5. Gradient Boosting

Accuracy: 73%

Precision: 72%

Recall: 75%

F1-score: 73%

ROC-AUC: 0.8087

Interpretación
Fue el modelo con mejor rendimiento global.
Obtuvo la mayor exactitud y el mejor ROC-AUC.
Tiene el mejor equilibrio entre precisión y recall.
Detecta correctamente una gran proporción de accidentes fatales sin sacrificar demasiado la precisión.
El ROC-AUC de 0.8087 muestra una muy buena capacidad de discriminación entre clases.
Este modelo aprende de los errores de árboles anteriores, lo que mejora progresivamente las predicciones.

preguntas

¿Dónde y bajo qué condiciones es más probable que un accidente de tránsito resulte fatal en Colombia?
"""

# Supuestos:
# - El modelo final (Gradient Boosting) ya está entrenado
# - El pipeline/modelo se llama: model
# - La base completa se llama: df
# - La variable objetivo es: fatal (1 = fatal, 0 = no fatal)
# ==========================================================

import pandas as pd
import matplotlib.pyplot as plt

# ==========================================================
# 1. VARIABLES UTILIZADAS EN EL MODELO
# ==========================================================
features = [
    "MARCA_VEHICULO",
    "MODELO_VEHICULO",
    "TIPO_VEHICULO",
    "EDAD_VEHICULO",
    "DEPARTAMENTO_ACCIDENTE",
    "MUNICIPIO_ACCIDENTE",
    "AUTORIDAD_DE_TRANSITO",
    "año",
    "mes"
]

# ==========================================================
# 2. CALCULAR PROBABILIDAD PREDICHA DE FATALIDAD
# ==========================================================
X_full = df[features]

# Probabilidad de que el accidente sea fatal
df["prob_fatal"] = best_model.predict_proba(X_full)[:, 1]

# ==========================================================
# 3. TOP 10 DEPARTAMENTOS CON MAYOR RIESGO
# ==========================================================
riesgo_departamento = (
    df.groupby("DEPARTAMENTO_ACCIDENTE")["prob_fatal"]
    .mean()
    .sort_values(ascending=False)
)

print("========== TOP 10 DEPARTAMENTOS CON MAYOR RIESGO ==========")
print(riesgo_departamento.head(10))

plt.figure(figsize=(10, 6))
riesgo_departamento.head(10).sort_values().plot(kind="barh")
plt.xlabel("Probabilidad promedio de fatalidad")
plt.ylabel("Departamento")
plt.title("Top 10 departamentos con mayor riesgo de accidentes fatales")
plt.tight_layout()
plt.show()

# ==========================================================
# 4. TOP 10 MUNICIPIOS CON MAYOR RIESGO
# ==========================================================
riesgo_municipio = (
    df.groupby("MUNICIPIO_ACCIDENTE")["prob_fatal"]
    .mean()
    .sort_values(ascending=False)
)

print("\n========== TOP 10 MUNICIPIOS CON MAYOR RIESGO ==========")
print(riesgo_municipio.head(10))

plt.figure(figsize=(10, 6))
riesgo_municipio.head(10).sort_values().plot(kind="barh")
plt.xlabel("Probabilidad promedio de fatalidad")
plt.ylabel("Municipio")
plt.title("Top 10 municipios con mayor riesgo de accidentes fatales")
plt.tight_layout()
plt.show()

# ==========================================================
# 5. TIPO DE VEHÍCULO CON MAYOR RIESGO
# ==========================================================
riesgo_tipo_vehiculo = (
    df.groupby("TIPO_VEHICULO")["prob_fatal"]
    .mean()
    .sort_values(ascending=False)
)

print("\n========== RIESGO POR TIPO DE VEHÍCULO ==========")
print(riesgo_tipo_vehiculo)

plt.figure(figsize=(10, 6))
riesgo_tipo_vehiculo.sort_values().plot(kind="barh")
plt.xlabel("Probabilidad promedio de fatalidad")
plt.ylabel("Tipo de vehículo")
plt.title("Probabilidad de fatalidad por tipo de vehículo")
plt.tight_layout()
plt.show()

# ==========================================================
# 6. MARCAS CON MAYOR RIESGO (TOP 10)
# ==========================================================
riesgo_marca = (
    df.groupby("MARCA_VEHICULO")["prob_fatal"]
    .mean()
    .sort_values(ascending=False)
)

print("\n========== TOP 10 MARCAS CON MAYOR RIESGO ==========")
print(riesgo_marca.head(10))

# ==========================================================
# 7. AUTORIDAD DE TRÁNSITO CON MAYOR RIESGO
# ==========================================================
riesgo_autoridad = (
    df.groupby("AUTORIDAD_DE_TRANSITO")["prob_fatal"]
    .mean()
    .sort_values(ascending=False)
)

print("\n========== RIESGO POR AUTORIDAD DE TRÁNSITO ==========")
print(riesgo_autoridad.head(10))

# ==========================================================
# 8. RIESGO POR MES
# ==========================================================
riesgo_mes = (
    df.groupby("mes")["prob_fatal"]
    .mean()
    .sort_values(ascending=False)
)

print("\n========== RIESGO POR MES ==========")
print(riesgo_mes)

plt.figure(figsize=(10, 6))
riesgo_mes.sort_index().plot(kind="bar")
plt.xlabel("Mes")
plt.ylabel("Probabilidad promedio de fatalidad")
plt.title("Probabilidad de fatalidad por mes")
plt.tight_layout()
plt.show()

# ==========================================================
# 9. ESCENARIO INDIVIDUAL CON MAYOR PROBABILIDAD
# ==========================================================
columnas_escenario = [
    "prob_fatal",
    "MARCA_VEHICULO",
    "MODELO_VEHICULO",
    "TIPO_VEHICULO",
    "EDAD_VEHICULO",
    "DEPARTAMENTO_ACCIDENTE",
    "MUNICIPIO_ACCIDENTE",
    "AUTORIDAD_DE_TRANSITO",
    "año",
    "mes"
]

escenario_max = (
    df[columnas_escenario]
    .sort_values("prob_fatal", ascending=False)
    .iloc[0]
)

print("\n========== ESCENARIO DE MAYOR RIESGO ==========")
print(f"Probabilidad estimada de fatalidad: {escenario_max['prob_fatal']:.2%}")
print(f"Marca del vehículo: {escenario_max['MARCA_VEHICULO']}")
print(f"Modelo del vehículo: {escenario_max['MODELO_VEHICULO']}")
print(f"Tipo de vehículo: {escenario_max['TIPO_VEHICULO']}")
print(f"Edad del vehículo: {escenario_max['EDAD_VEHICULO']} años")
print(f"Departamento: {escenario_max['DEPARTAMENTO_ACCIDENTE']}")
print(f"Municipio: {escenario_max['MUNICIPIO_ACCIDENTE']}")
print(f"Autoridad de tránsito: {escenario_max['AUTORIDAD_DE_TRANSITO']}")
print(f"Año: {escenario_max['año']}")
print(f"Mes: {escenario_max['mes']}")

# ==========================================================
# 10. TOP 10 ESCENARIOS MÁS RIESGOSOS
# ==========================================================
top_10_escenarios = (
    df[columnas_escenario]
    .sort_values("prob_fatal", ascending=False)
    .head(10)
)

print("\n========== TOP 10 ESCENARIOS MÁS RIESGOSOS ==========")
print(top_10_escenarios)

# ==========================================================
# 11. GUARDAR RESULTADOS
# ==========================================================
riesgo_departamento.to_csv("riesgo_por_departamento.csv")
riesgo_municipio.to_csv("riesgo_por_municipio.csv")
riesgo_tipo_vehiculo.to_csv("riesgo_por_tipo_vehiculo.csv")
top_10_escenarios.to_csv("top_10_escenarios_mas_riesgosos.csv", index=False)

print("\nArchivos guardados:")
print("- riesgo_por_departamento.csv")
print("- riesgo_por_municipio.csv")
print("- riesgo_por_tipo_vehiculo.csv")
print("- top_10_escenarios_mas_riesgosos.csv")

m

fig, ax = plt.subplots(1, 1, figsize=(12, 8))
colombia_accidentes.plot(
    column='PROB_FATAL',
    cmap='YlOrRd', # A sequential colormap for risk
    linewidth=0.8,
    ax=ax,
    edgecolor='0.8',
    legend=True,
    legend_kwds={'label': "Probabilidad de Fatalidad", 'orientation': "horizontal"},
    missing_kwds={
        "color": "lightgrey",
        "edgecolor": "red",
        "hatch": "///",
        "label": "Sin datos"
    }
)
colombia_accidentes.boundary.plot(ax=ax, color='black', linewidth=0.5)
ax.set_title('Mapa de Calor de Riesgo de Fatalidad por Departamento (2022-2026)', fontsize=15)
ax.set_axis_off()
plt.show()